language: android
android:
  components:
    - build-tools-27.0.2

    - android-27

    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    - sys-img-armeabi-v7a-android-27
    - sys-img-armeabi-v7a-android-25
    - sys-img-armeabi-v7a-android-22

script:
  - ./gradlew clean assemble --stacktrace
  - ./gradlew test --no-rebuild --continue --stacktrace